name: Deploy to gh-pages

on:
    push:
        branches: [main]

permissions:
    contents: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
              with:
                  ref: main

            - name: Checkout gh-pages branch
              uses: actions/checkout@v3
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Sync dist to pages
              run: |
                  rm -rf ./gh-pages/pages/ || true
                  mkdir -p ./gh-pages/pages/
                  cp -r ./dist/* ./gh-pages/pages/
                  cp -r ./gh-pages/public/* ./gh-pages/pages/ || true

            - name: Commit & Push to pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cd ./gh-pages/
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add ./pages/
                  git status
                  if git diff --cached --quiet; then
                    echo "No changes."
                    exit 0
                  fi
                  git commit -m "✅Deploy from main"
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/hi2ma-bu4/bio.git HEAD:gh-pages

    notify-parent:
        runs-on: ubuntu-latest
        steps:
            - name: Dispatch event to gh-pages
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: static_pages
